In [1]:
import os

In [2]:
import numpy as np
import cv2
from tensorflow.keras.utils import to_categorical

from keras.layers import Input, Dense 
from keras.models import Model

In [3]:
import cv2
import mediapipe as mp
import tensorflow as tf
import numpy as np

print("NumPy:", np.__version__)
print("TensorFlow:", tf.__version__)
print("MediaPipe:", mp.__version__)
print("All imports working ✅")


NumPy: 1.24.3
TensorFlow: 2.13.0
MediaPipe: 0.10.5
All imports working ✅


In [4]:
is_init = False
size = -1

label = []
dictionary = {}
c = 0

for i in os.listdir():
    if i.split(".")[-1] == "npy" and not(i.split(".")[0] == "labels"):  
        if not(is_init):
            is_init = True 
            X = np.load(i)
            size = X.shape[0]
            y = np.array([i.split('.')[0]]*size).reshape(-1,1)
        else:
            X = np.concatenate((X, np.load(i)))
            y = np.concatenate((y, np.array([i.split('.')[0]]*size).reshape(-1,1)))

        label.append(i.split('.')[0])
        dictionary[i.split('.')[0]] = c  
        c = c+1


for i in range(y.shape[0]):
    y[i, 0] = dictionary[y[i, 0]]
y = np.array(y, dtype="int32")

###  hello = 0 nope = 1 ---> [1,0] ... [0,1]

y = to_categorical(y)

X_new = X.copy()
y_new = y.copy()
counter = 0 

cnt = np.arange(X.shape[0])
np.random.shuffle(cnt)

for i in cnt: 
    X_new[counter] = X[i]
    y_new[counter] = y[i]
    counter = counter + 1


ip = Input(shape=(X.shape[1]))

m = Dense(512, activation="relu")(ip)
m = Dense(256, activation="relu")(m)

op = Dense(y.shape[1], activation="softmax")(m) 

model = Model(inputs=ip, outputs=op)

model.compile(optimizer='rmsprop', loss="categorical_crossentropy", metrics=['acc'])

model.fit(X, y, epochs=50)


model.save("model.h5")
np.save("labels.npy", np.array(label))


Epoch 1/50
29/29 [==============================] - 2s 14ms/step - loss: 1.8254 - acc: 0.3156
Epoch 2/50
29/29 [==============================] - 0s 12ms/step - loss: 1.1910 - acc: 0.5889
Epoch 3/50
29/29 [==============================] - 0s 12ms/step - loss: 0.9316 - acc: 0.6822
Epoch 4/50
29/29 [==============================] - 0s 13ms/step - loss: 0.7193 - acc: 0.7767
Epoch 5/50
29/29 [==============================] - 0s 12ms/step - loss: 0.6394 - acc: 0.7922
Epoch 6/50
29/29 [==============================] - 0s 13ms/step - loss: 0.5233 - acc: 0.8556
Epoch 7/50
29/29 [==============================] - 0s 13ms/step - loss: 0.4761 - acc: 0.8578
Epoch 8/50
29/29 [==============================] - 0s 13ms/step - loss: 0.3976 - acc: 0.8844
Epoch 9/50
29/29 [==============================] - 0s 13ms/step - loss: 0.3868 - acc: 0.8867
Epoch 10/50
29/29 [==============================] - 0s 13ms/step - loss: 0.3441 - acc: 0.8822
Epoch 11/50
29/29 [==============================] - 0s 13m

c:\users\pc\downloads\emotion-based-music-recommender\venv\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [5]:
print(X)
print(y)

[[ 2.45302916e-04  4.30118442e-02  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-2.31504440e-04  4.19347882e-02  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-7.78436661e-04  4.07878160e-02  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 2.27463245e-03  6.34168088e-02  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 6.89685345e-04  6.36338592e-02  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-8.39829445e-05  6.31835163e-02  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]]
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
